### ISSUE TITLE
[Q&A] 想咨询一下关于 WEB（trtc-sdk-v5） 端与 Uni-app(TUICallKit) 端通讯问题

### ISSUE THREAD

**Issue by menkan** [Tencent-RTC/TRTC_Web#121]
【问题背景】
我们项目在 WEB（` trtc-sdk-v5`） 端，尝试与 uni-app（`tui-call-kit`） 端通讯。

`trtc-sdk-v5` 采用进入 enterRoom 方法创建房间等待其他用户进入，而 `tui-call-kit` 采用 call 方法进行呼叫用户。

此处   `tui-call-kit` 的官方文档上写着 需要被呼叫方 采用 `accept` 方法响应请求方回调才会进行音视频推流。

【咨询问题】
想咨询一下 如何在 `trtc-sdk-v5` 上进行响应对方的呼叫（执行`accept`）。让对方顺利的进行视频推流呢

Tips: 目前 `trtc-sdk-v5` 端启动房间。`tui-call-kit` 通过 `call` 可以接收到对方推流，但是无法推送自己的音视频流到 `trtc-skd-v5`

**Comment by Rychou** [comment]
@menkan  这个用法比较奇怪，一般 TUICallKit 和 trtc-sdk-v5 不会混用，先了解一下您的场景，为什么不都用 TUICallKit 呢？

**Comment by menkan** [comment]
@Rychou 
【原因】
您好，我这边在 WEB 采用 trtc-sdk-v5 是想要更好的功能定制化，可自定义性更强（想兼容1v1通讯，多人通讯）
TUICallKit (Ui) 用在了移动端、想的是官方提供的 ui 集成更好，移动端可以少做功能自定义。

【目前解决方案】
因为目前 TUICallKit 存在 call 方法 调用 等待响应的原因，我们把 TUICallKit 更换成了 TUIRoomKit 方案。这样加入房间就“跳过了” call 方法的等待响应 （accept）问题。

**Comment by Rychou** [comment]
@menkan 好的， TUICallKit 和 TUIRoomKit 是基于 trtc-sdk-v5 实现的，由于 TUIKit 有会控等业务逻辑，无法畅快地实现和 trtc-sdk-v5 的互通。

**Comment by menkan** [comment]
感谢回复，感谢解答
